import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/app/components/Header";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;

const pretendard = localFont({
  src: "./fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // 쿠키나 로컬 스토리지로 테마 관리 가능
  const theme = typeof window !== "undefined" && localStorage.getItem("theme");
  return (
    <html lang="ko" className={theme === "dark" ? "dark" : ""}>
      <body className={`${pretendard.className}  antialiased`}>
        <Header />
        <main className="mt-[72px]">{children}</main>
      </body>
    </html>
  );
}
